// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWQLLGDXjDZ8pycucsPfkk9Ovw5uqg0w',
    appId: '1:50299541997:web:190b205f6dbe13550dafe4',
    messagingSenderId: '50299541997',
    projectId: 'zymbiot-6b136',
    authDomain: 'zymbiot-6b136.firebaseapp.com',
    databaseURL: 'https://zymbiot-6b136-default-rtdb.firebaseio.com',
    storageBucket: 'zymbiot-6b136.firebasestorage.app',
    measurementId: 'G-1Z58TE5K2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJeRiSZY09R15MGvukxce3DJYNmEyrm8',
    appId: '1:50299541997:android:34236a5bc53a36d70dafe4',
    messagingSenderId: '50299541997',
    projectId: 'zymbiot-6b136',
    databaseURL: 'https://zymbiot-6b136-default-rtdb.firebaseio.com',
    storageBucket: 'zymbiot-6b136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjreTt8Zl9qqBwjk9m-hnHfua_7-M72Q',
    appId: '1:50299541997:ios:6fdfca2a5b6386d90dafe4',
    messagingSenderId: '50299541997',
    projectId: 'zymbiot-6b136',
    databaseURL: 'https://zymbiot-6b136-default-rtdb.firebaseio.com',
    storageBucket: 'zymbiot-6b136.firebasestorage.app',
    iosClientId: '50299541997-s4uqpt8eum2f0l3dk8spqu8tq83r7mon.apps.googleusercontent.com',
    iosBundleId: 'com.example.zymbiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGjreTt8Zl9qqBwjk9m-hnHfua_7-M72Q',
    appId: '1:50299541997:ios:6fdfca2a5b6386d90dafe4',
    messagingSenderId: '50299541997',
    projectId: 'zymbiot-6b136',
    databaseURL: 'https://zymbiot-6b136-default-rtdb.firebaseio.com',
    storageBucket: 'zymbiot-6b136.firebasestorage.app',
    iosClientId: '50299541997-s4uqpt8eum2f0l3dk8spqu8tq83r7mon.apps.googleusercontent.com',
    iosBundleId: 'com.example.zymbiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByWQLLGDXjDZ8pycucsPfkk9Ovw5uqg0w',
    appId: '1:50299541997:web:3870bb48e64ebe390dafe4',
    messagingSenderId: '50299541997',
    projectId: 'zymbiot-6b136',
    authDomain: 'zymbiot-6b136.firebaseapp.com',
    databaseURL: 'https://zymbiot-6b136-default-rtdb.firebaseio.com',
    storageBucket: 'zymbiot-6b136.firebasestorage.app',
    measurementId: 'G-NNRFWM5L97',
  );
}
